apiVersion: batch/v1
kind: Job
metadata:
  name: postsync-notify
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: notify
        image: busybox
        command:
        - sh
        - -c
        - |
          echo "PostSync Hook: Deployment Complete!"
          echo "All waves deployed successfully."
          echo "Sending Notifcation (In real world slack, gmail etc)"
          sleep 2
          echo "Notification Sent"
      restartPolicy: Never
  backoffLimit: 1